### ISSUE TITLE
predict_proba signature when using ci

### ISSUE THREAD

**Issue by JonasHanselle** [TRR318/scikit-psl#40]
When setting the ci parameter of predict_proba the result is a nx3 array with the lower bound, mid point and upper bound of  the Clopper Pearson confidence interval. I think this is not strictly compatible with sklearn use of predict_proba, which returns the point probability estimate per class.

**Comment by stheid** [comment]
you are right, thats incompatible, but it only returns this nx3 array if this optional parameter is supplied, which sklearn would never do. hence the predict_proba should behave properly in the context of sklearn, while superseeding the standard

**Comment by JonasHanselle** [comment]
Doesn't it violate the principle of least surprise for sklearn users? Additionally, why would you never set the optional parameter when using it in conjunction with other sklearn components?
